# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/microblaze.xdc

# Block Designs: bd/handgesture_mb/handgesture_mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb || ORIG_REF_NAME==handgesture_mb} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_microblaze_0_0/handgesture_mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_microblaze_0_0 || ORIG_REF_NAME==handgesture_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_microblaze_0_axi_periph_0/handgesture_mb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==handgesture_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_microblaze_0_axi_intc_0/handgesture_mb_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_microblaze_0_axi_intc_0 || ORIG_REF_NAME==handgesture_mb_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_microblaze_0_xlconcat_0/handgesture_mb_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_microblaze_0_xlconcat_0 || ORIG_REF_NAME==handgesture_mb_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_mdm_1_0/handgesture_mb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_mdm_1_0 || ORIG_REF_NAME==handgesture_mb_mdm_1_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_clk_wiz_1_0/handgesture_mb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_clk_wiz_1_0 || ORIG_REF_NAME==handgesture_mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_rst_clk_wiz_1_100M_0/handgesture_mb_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==handgesture_mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_0_0/handgesture_mb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_axi_uartlite_0_0 || ORIG_REF_NAME==handgesture_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_axi_gpio_0_0/handgesture_mb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_axi_gpio_0_0 || ORIG_REF_NAME==handgesture_mb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_axi_gpio_1_0/handgesture_mb_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_axi_gpio_1_0 || ORIG_REF_NAME==handgesture_mb_axi_gpio_1_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_xbar_0/handgesture_mb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_xbar_0 || ORIG_REF_NAME==handgesture_mb_xbar_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_dlmb_v10_0/handgesture_mb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_dlmb_v10_0 || ORIG_REF_NAME==handgesture_mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_ilmb_v10_0/handgesture_mb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_ilmb_v10_0 || ORIG_REF_NAME==handgesture_mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_dlmb_bram_if_cntlr_0/handgesture_mb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==handgesture_mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_ilmb_bram_if_cntlr_0/handgesture_mb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==handgesture_mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_lmb_bram_0/handgesture_mb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_lmb_bram_0 || ORIG_REF_NAME==handgesture_mb_lmb_bram_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_1_0/handgesture_mb_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_axi_uartlite_1_0 || ORIG_REF_NAME==handgesture_mb_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/handgesture_mb/ip/handgesture_mb_myip_slave2_0_0/handgesture_mb_myip_slave2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==handgesture_mb_myip_slave2_0_0 || ORIG_REF_NAME==handgesture_mb_myip_slave2_0_0} -quiet] -quiet

# XDC: bd/handgesture_mb/handgesture_mb_ooc.xdc
