# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.cache/wt [current_project]
set_property parent.project_path C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/PC/Desktop/FinalProjectECE532/ip_repo [current_project]
set_property ip_output_repo c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/hdl/handgesture_mb_wrapper.v
add_files C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/handgesture_mb.bd
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_microblaze_0_0/handgesture_mb_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_microblaze_0_0/handgesture_mb_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_microblaze_0_0/handgesture_mb_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_microblaze_0_axi_intc_0/handgesture_mb_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_microblaze_0_axi_intc_0/handgesture_mb_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_microblaze_0_axi_intc_0/handgesture_mb_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_mdm_1_0/handgesture_mb_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_mdm_1_0/handgesture_mb_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_clk_wiz_1_0/handgesture_mb_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_clk_wiz_1_0/handgesture_mb_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_clk_wiz_1_0/handgesture_mb_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_rst_clk_wiz_1_100M_0/handgesture_mb_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_rst_clk_wiz_1_100M_0/handgesture_mb_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_rst_clk_wiz_1_100M_0/handgesture_mb_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_0_0/handgesture_mb_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_0_0/handgesture_mb_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_0_0/handgesture_mb_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_gpio_0_0/handgesture_mb_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_gpio_0_0/handgesture_mb_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_gpio_0_0/handgesture_mb_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_gpio_1_0/handgesture_mb_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_gpio_1_0/handgesture_mb_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_gpio_1_0/handgesture_mb_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_xbar_0/handgesture_mb_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_dlmb_v10_0/handgesture_mb_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_dlmb_v10_0/handgesture_mb_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_ilmb_v10_0/handgesture_mb_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_ilmb_v10_0/handgesture_mb_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_dlmb_bram_if_cntlr_0/handgesture_mb_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_ilmb_bram_if_cntlr_0/handgesture_mb_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_lmb_bram_0/handgesture_mb_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_1_0/handgesture_mb_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_1_0/handgesture_mb_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/ip/handgesture_mb_axi_uartlite_1_0/handgesture_mb_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/sources_1/bd/handgesture_mb/handgesture_mb_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/constrs_1/new/microblaze.xdc
set_property used_in_implementation false [get_files C:/Users/PC/Desktop/FinalProjectECE532/handgesture/handgesture.srcs/constrs_1/new/microblaze.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top handgesture_mb_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef handgesture_mb_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file handgesture_mb_wrapper_utilization_synth.rpt -pb handgesture_mb_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
